# Generated by Django 5.0.6 on 2024-06-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_organisateur_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='categorie',
            field=models.CharField(choices=[('ligue 1', 'ligue 1'), ('ligue 2', 'ligue 2'), ('Coupe du tunisie', 'Coupe du tunisie'), ('Amateur ligue', 'Amateur ligue')], max_length=255),
        ),
    ]
